use sqlx::PgPool;
use crate::error::AppError;

/// Reverse-engineer a CREATE TABLE statement for the given table.
pub async fn generate_create_table(
    pool: &PgPool,
    schema: &str,
    table: &str,
) -> Result<String, AppError> {
    use sqlx::Row;

    // Check if view or materialized view
    let kind_sql = r#"
        SELECT c.relkind::text, pg_get_viewdef(c.oid, true)
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = $1 AND c.relname = $2
    "#;
    
    let kind_row = sqlx::query(kind_sql)
        .bind(schema)
        .bind(table)
        .fetch_optional(pool)
        .await?;

    if let Some(r) = kind_row {
        let relkind: String = r.get(0);
        let view_def: Option<String> = r.get(1);
        
        if relkind == "v" || relkind == "m" {
            let def = view_def.unwrap_or_default();
            let ddl = if relkind == "v" {
                format!(
                    "-- View: {}.{}\n\nCREATE OR REPLACE VIEW {}.{} AS\n{}",
                    quote_ident(schema),
                    quote_ident(table),
                    quote_ident(schema),
                    quote_ident(table),
                    def
                )
            } else {
                format!(
                    "-- Materialized View: {}.{}\n\nCREATE MATERIALIZED VIEW {}.{} AS\n{}",
                    quote_ident(schema),
                    quote_ident(table),
                    quote_ident(schema),
                    quote_ident(table),
                    def
                )
            };
            return Ok(ddl);
        }
    }

    let mut ddl = String::new();

    // Get column definitions
    let columns_sql = r#"
        SELECT
            a.attname AS name,
            format_type(a.atttypid, a.atttypmod) AS data_type,
            a.attnotnull AS not_null,
            pg_get_expr(ad.adbin, ad.adrelid) AS default_value,
            a.attidentity != '' AS is_identity,
            pg_catalog.col_description(a.attrelid, a.attnum) AS comment,
            a.attnum AS position
        FROM pg_attribute a
        JOIN pg_class c ON c.oid = a.attrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
        WHERE n.nspname = $1 AND c.relname = $2
          AND a.attnum > 0 AND NOT a.attisdropped
        ORDER BY a.attnum
    "#;

    let columns: Vec<ColumnDef> = sqlx::query_as::<_, ColumnDef>(columns_sql)
        .bind(schema)
        .bind(table)
        .fetch_all(pool)
        .await?;

    // Get primary key columns
    let pk_sql = r#"
        SELECT a.attname
        FROM pg_index i
        JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
        JOIN pg_class c ON c.oid = i.indrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = $1 AND c.relname = $2 AND i.indisprimary
        ORDER BY array_position(i.indkey, a.attnum)
    "#;

    let pk_cols: Vec<String> = sqlx::query_scalar::<_, String>(pk_sql)
        .bind(schema)
        .bind(table)
        .fetch_all(pool)
        .await?;

    // Get constraints (excluding PK which we handle separately)
    let constraints_sql = r#"
        SELECT
            conname AS name,
            contype::text AS contype,
            pg_get_constraintdef(oid) AS definition
        FROM pg_constraint
        WHERE conrelid = (
            SELECT c.oid FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = $1 AND c.relname = $2
        )
        ORDER BY contype, conname
    "#;

    let constraints: Vec<ConstraintRow> = sqlx::query_as::<_, ConstraintRow>(constraints_sql)
        .bind(schema)
        .bind(table)
        .fetch_all(pool)
        .await?;

    // Build DDL
    ddl.push_str(&format!(
        "-- Table: {}.{}\n\n",
        quote_ident(schema),
        quote_ident(table)
    ));
    ddl.push_str(&format!(
        "CREATE TABLE {}.{} (\n",
        quote_ident(schema),
        quote_ident(table)
    ));

    let mut col_defs: Vec<String> = Vec::new();
    for col in &columns {
        let mut def = format!("    {}", quote_ident(&col.name));
        def.push(' ');
        def.push_str(&col.data_type);

        if let Some(ref default_val) = col.default_value {
            def.push_str(&format!(" DEFAULT {}", default_val));
        }
        if col.not_null {
            def.push_str(" NOT NULL");
        }
        if col.is_identity {
            def.push_str(" GENERATED BY DEFAULT AS IDENTITY");
        }

        // Add column comment
        if let Some(ref comment) = col.comment {
            def.push_str(&format!(" -- {}", comment));
        }
        col_defs.push(def);
    }

    // Primary key
    if !pk_cols.is_empty() {
        col_defs.push(format!(
            "    PRIMARY KEY ({})",
            pk_cols.iter().map(|c| quote_ident(c)).collect::<Vec<_>>().join(", ")
        ));
    }

    // UNIQUE constraints (from constraint rows where contype = 'u')
    for c in &constraints {
        if c.contype == "u" {
            col_defs.push(format!("    CONSTRAINT {} {}", quote_ident(&c.name), c.definition));
        }
    }

    // CHECK constraints
    for c in &constraints {
        if c.contype == "c" {
            col_defs.push(format!("    CONSTRAINT {} {}", quote_ident(&c.name), c.definition));
        }
    }

    ddl.push_str(&col_defs.join(",\n"));
    ddl.push_str("\n);");

    // Foreign keys (as ALTER TABLE)
    for c in &constraints {
        if c.contype == "f" {
            ddl.push_str(&format!(
                "\nALTER TABLE {}.{} ADD CONSTRAINT {} {};\n",
                quote_ident(schema),
                quote_ident(table),
                quote_ident(&c.name),
                c.definition
            ));
        }
    }

    // Indexes (excluding PK which is auto-created)
    let indexes_sql = r#"
        SELECT
            c2.relname AS name,
            pg_get_indexdef(i.indexrelid) AS definition
        FROM pg_index i
        JOIN pg_class c ON c.oid = i.indrelid
        JOIN pg_class c2 ON c2.oid = i.indexrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = $1 AND c.relname = $2 AND NOT i.indisprimary
        ORDER BY c2.relname
    "#;

    let indexes: Vec<IndexRow> = sqlx::query_as::<_, IndexRow>(indexes_sql)
        .bind(schema)
        .bind(table)
        .fetch_all(pool)
        .await?;

    for idx in &indexes {
        ddl.push_str(&format!("{};\n", idx.definition));
    }

    // Table comment
    let comment_sql = r#"
        SELECT pg_catalog.obj_description(c.oid, 'pg_class')
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = $1 AND c.relname = $2
    "#;

    let comment: Option<String> = sqlx::query_scalar(comment_sql)
        .bind(schema)
        .bind(table)
        .fetch_optional(pool)
        .await?
        .flatten();

    if let Some(ref cmt) = comment {
        ddl.push_str(&format!(
            "\nCOMMENT ON TABLE {}.{} IS '{}';\n",
            quote_ident(schema),
            quote_ident(table),
            cmt.replace('\'', "''")
        ));
    }

    Ok(ddl)
}

/// Generate a SELECT template for a table.
pub fn generate_select(
    schema: &str,
    table: &str,
    columns: &[String],
) -> String {
    let col_list = if columns.is_empty() {
        "*".to_string()
    } else if columns.len() <= 8 {
        columns.iter().map(|c| quote_ident(c)).collect::<Vec<_>>().join(", ")
    } else {
        columns.iter().map(|c| quote_ident(c)).collect::<Vec<_>>().join(",\n  ")
    };

    if columns.len() > 8 {
        format!(
            "SELECT\n  {}\nFROM {}.{}\nLIMIT 100;",
            col_list,
            quote_ident(schema),
            quote_ident(table)
        )
    } else {
        format!(
            "SELECT {} FROM {}.{} LIMIT 100;",
            col_list,
            quote_ident(schema),
            quote_ident(table)
        )
    }
}

/// Generate an INSERT template for a table.
pub fn generate_insert(
    schema: &str,
    table: &str,
    columns: &[String],
) -> String {
    let col_list = columns.iter().map(|c| quote_ident(c)).collect::<Vec<_>>().join(", ");
    let placeholders = columns.iter().enumerate()
        .map(|(i, _)| format!("${{{}:value_{}}}", i + 1, i + 1))
        .collect::<Vec<_>>().join(", ");

    format!(
        "INSERT INTO {}.{} ({})\nVALUES ({});",
        quote_ident(schema),
        quote_ident(table),
        col_list,
        placeholders
    )
}

fn quote_ident(name: &str) -> String {
    if name.contains('"') || name.contains(char::is_uppercase) || name.contains(' ') {
        format!("\"{}\"", name)
    } else {
        name.to_string()
    }
}

// --- Row types for queries ---

#[derive(sqlx::FromRow)]
struct ColumnDef {
    name: String,
    data_type: String,
    not_null: bool,
    default_value: Option<String>,
    is_identity: bool,
    comment: Option<String>,
}

#[derive(sqlx::FromRow)]
struct ConstraintRow {
    name: String,
    contype: String,
    definition: String,
}

#[derive(sqlx::FromRow)]
struct IndexRow {
    #[allow(dead_code)]
    name: String,
    definition: String,
}
